---
resources:
  - name: accounts-git
    type: git
    source:
      uri: git@github.com:openstax/accounts.git
      private_key: ((github-private-key))
      branch: new_deployment

  - name: concourse-pipelines
    type: git
    source:
      uri: https://github.com/openstax/concourse-pipelines.git
      branch: accounts-new-deploy-automation

jobs:
  - name: build-accounts-ami
    plan:
      - get: accounts-git
        trigger: true

      - get: concourse-pipelines

      - task: Build Accounts AMI
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              username: ((docker-hub-username))
              password: ((docker-hub-password))
              repository: openstaxdevops/accounts-deployment

          inputs:
            - name: accounts-git
            - name: concourse-pipelines
          outputs:
            - name: accounts-ami-built
          run:
            path: concourse-pipelines/accounts/accounts-build-ami.sh

        params:
          SHA: accounts-git/.git/ref
