---
resources:
  - name: accounts-deployment-git
    type: git
    source:
      uri: git@github.com:/openstax/devops
      branch: tutor-deployment-update
      private_key: ((github-private-key))

  - name: accounts-deployment-docker-image
    type: docker-image
    source:
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: openstaxdevops/accounts-deployment


jobs:
  - name: publish
    plan:
      - get: accounts-deployment-git
        trigger: true
      - put: accounts-deployment-docker-image
        params:
          build: accounts-deployment-git/new_deployments/apps/accounts
