version: '3.7'
services:
  concourse-db:
    image: postgres:12
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev

  concourse:
    image: concourse/concourse:4.2.2
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: dev
      CONCOURSE_POSTGRES_PASSWORD: dev
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: dev:dev
      CONCOURSE_MAIN_TEAM_LOCAL_USER: dev
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay

  docker-registry:
    restart: always
    image: registry:2
    ports: ["5000:5000"]

  git-server:
    image: tomjw64/git-server
    ports: ["8090:8000"]
