# A pipeline used to automatically tag cnx-deploy when a merge to master occurs
# and publish the tag to GitHub.
---

resources:
  - name: cnx-deploy
    type: git
    source:
      uri: git@github.com:openstax/cnx-deploy.git
      private_key: ((github-private-key))
      branch: master

  - name: concourse-pipelines
    type: git
    source:
      uri: https://github.com/openstax/concourse-pipelines.git

jobs:
  - name: tag-cnx-deploy
    plan:
      - get: cnx-deploy
        trigger: true
      
      - get: concourse-pipelines

      - task: tag-n-publish-cnx-deploy
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python:3.8-slim

          inputs:
            - name: cnx-deploy
            - name: concourse-pipelines
          run:
            path: concourse-pipelines/tag-cnx-deploy/tag.sh
        params:
          GIT_PRIVATE_KEY: ((github-private-key))
          GIT_USER_EMAIL: ((github-username))
          GIT_USER_NAME: ((github-username))
