---
docker-credentials: &docker-credentials
  username: ((ce-dockerhub-id))
  password: ((ce-dockerhub-token))

ecr-credentials: &ecr-credentials
  aws_secret_access_key: ((ce_ecr_user_access_key))
  aws_access_key_id: ((ce_ecr_user_access_key_id))

image-build-config-common: &image-build-config-common
  platform: linux
  outputs: [{ name: image }]
  caches: [{ path: cache }]
  run: { path: build }

resources:
  - name: image-builder
    type: registry-image
    source:
      repository: concourse/oci-build-task
      tag: latest
      <<: *docker-credentials

  - name: source-code-nebuchadnezzar
    type: git
    source:
      uri: https://github.com/openstax/nebuchadnezzar.git
      branch: master
  - name: docker-hub-image-nebuchadnezzar
    type: registry-image
    source:
      repository: openstax/nebuchadnezzar
      <<: *docker-credentials
  - name: ecr-image-nebuchadnezzar
    type: registry-image
    source:
      repository: 258998078732.dkr.ecr.us-east-2.amazonaws.com/nebuchadnezzar
      <<: *ecr-credentials

  - name: source-code-cops
    type: git
    source:
      uri: https://github.com/openstax/output-producer-service.git
      branch: master
  - name: docker-hub-image-cops-frontend
    type: registry-image
    source:
      repository: openstax/output-producer-frontend
      <<: *docker-credentials
  - name: ecr-image-corgi-frontend
    type: registry-image
    source:
      repository: 258998078732.dkr.ecr.us-east-2.amazonaws.com/corgi-frontend
      <<: *ecr-credentials
  

  - name: docker-hub-image-cops-backend
    type: registry-image
    source:
      repository: openstax/output-producer-backend
      <<: *docker-credentials
  - name: ecr-image-corgi-backend
    type: registry-image
    source:
      repository: 258998078732.dkr.ecr.us-east-2.amazonaws.com/corgi-backend
      <<: *ecr-credentials

  - name: docker-hub-image-cops-bakery-scripts
    type: registry-image
    source:
      repository: openstax/cops-bakery-scripts
      <<: *docker-credentials
  - name: ecr-image-corgi-bakery-scripts
    type: registry-image
    source:
      repository: 258998078732.dkr.ecr.us-east-2.amazonaws.com/corgi-bakery-scripts
      <<: *ecr-credentials

  - name: source-code-mathify
    type: git
    source:
      uri: https://github.com/openstax/mathify.git
      branch: master
  - name: docker-hub-image-mathify
    type: registry-image
    source:
      repository: openstax/mathify
      <<: *docker-credentials
  - name: ecr-image-mathify
    type: registry-image
    source:
      repository: 258998078732.dkr.ecr.us-east-2.amazonaws.com/mathify
      <<: *ecr-credentials

  - name: source-code-princexml
    type: git
    source:
      uri: https://github.com/openstax/docker-princexml.git
      branch: master
  - name: docker-hub-image-princexml
    type: registry-image
    source:
      repository: openstax/princexml
      <<: *docker-credentials
  - name: ecr-image-princexml
    type: registry-image
    source:
      repository: 258998078732.dkr.ecr.us-east-2.amazonaws.com/princexml
      <<: *ecr-credentials

  - name: source-code-cops-resource
    type: git
    source:
      uri: https://github.com/openstax/output-producer-resource.git
      branch: master
  - name: docker-hub-image-cops-resource
    type: registry-image
    source:
      repository: openstax/output-producer-resource
      <<: *docker-credentials
  - name: ecr-image-corgi-resource
    type: registry-image
    source:
      repository: 258998078732.dkr.ecr.us-east-2.amazonaws.com/corgi-resource
      <<: *ecr-credentials

  - name: source-code-cnx-recipes
    type: git
    source:
      uri: https://github.com/openstax/cnx-recipes.git
      branch: master
      tag_filter: '*'
  - name: docker-hub-image-cnx-recipes-output
    type: registry-image
    source:
      repository: openstax/cnx-recipes-output
      <<: *docker-credentials
  - name: ecr-image-cnx-recipes-output
    type: registry-image
    source:
      repository: 258998078732.dkr.ecr.us-east-2.amazonaws.com/cnx-recipes-output
      <<: *ecr-credentials

  - name: source-code-kitchen-recipes
    type: git
    source:
      uri: https://github.com/openstax/recipes.git
      branch: main
      tag_filter: '*'
  - name: docker-hub-image-kitchen-recipes
    type: registry-image
    source:
      repository: openstax/recipes
      <<: *docker-credentials
  - name: ecr-image-kitchen-recipes
    type: registry-image
    source:
      repository: 258998078732.dkr.ecr.us-east-2.amazonaws.com/recipes
      <<: *ecr-credentials

  - name: source-code-xhtml-validator
    type: git
    source:
      uri: https://github.com/openstax/xhtml-validator.git
      branch: trunk
  - name: docker-hub-image-xhtml-validator
    type: registry-image
    source:
      repository: openstax/xhtml-validator
      <<: *docker-credentials
- name: ecr-image-xhtml-validator
    type: registry-image
    source:
      repository: 258998078732.dkr.ecr.us-east-2.amazonaws.com/xhtml-validator
      <<: *ecr-credentials

jobs:
  - name: build-and-publish-images
    build_log_retention:
      days: 7
      builds: 3
      minimum_succeeded_builds: 1
    public: true
    serial: true
    plan:
      - in_parallel:
        - get: image-builder
        - get: source-code-nebuchadnezzar
          trigger: true
        - get: source-code-cops
          trigger: true
        - get: source-code-mathify
          trigger: true
        - get: source-code-princexml
          trigger: true
        - get: source-code-cops-resource
          trigger: true
        - get: source-code-cnx-recipes
          trigger: true
        - get: source-code-kitchen-recipes
          trigger: true
        - get: source-code-xhtml-validator
          trigger: true
      # Use this task until buildkit + oci-build-task support docker hub auth
      - task: generate-dockerhub-config
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
              <<: *docker-credentials
          outputs: [{ name: docker-config }]
          params:
            DOCKER_USERNAME: ((ce-dockerhub-id))
            DOCKER_PASSWORD: ((ce-dockerhub-token))
          run:
            path: /bin/sh
            args:
              - -c
              - |
                AUTH="$(echo -n "$DOCKER_USERNAME:$DOCKER_PASSWORD" | base64)"
                cat > docker-config/config.json <<EOF
                { "auths": { "https://index.docker.io/v1/": { "auth": "$AUTH", "email": "devops@openstax.org" }}}
                EOF
      - task: report-versions-and-create-tag
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine/git
              <<: *docker-credentials
          inputs:
            - name: source-code-nebuchadnezzar
            - name: source-code-cops
            - name: source-code-mathify
            - name: source-code-princexml
            - name: source-code-cops-resource
            - name: source-code-cnx-recipes
            - name: source-code-kitchen-recipes
            - name: source-code-xhtml-validator
          outputs:
            - name: tags
            - name: labels
          run:
            path: /bin/sh
            args:
              - -cxe
              - |
                echo revision_nebuchadnezzar=$(git --git-dir=source-code-nebuchadnezzar/.git rev-parse --short HEAD) >> labels/labels
                echo revision_cops=$(git --git-dir=source-code-cops/.git rev-parse --short HEAD) >> labels/labels
                echo revision_mathify=$(git --git-dir=source-code-mathify/.git rev-parse --short HEAD) >> labels/labels
                echo revision_princexml=$(git --git-dir=source-code-princexml/.git rev-parse --short HEAD) >> labels/labels
                echo revision_cops_resource=$(git --git-dir=source-code-cops-resource/.git rev-parse --short HEAD) >> labels/labels
                echo revision_cnx_recipes=$(git --git-dir=source-code-cnx-recipes/.git rev-parse --short HEAD) >> labels/labels
                echo revision_kitchen_recipes=$(git --git-dir=source-code-kitchen-recipes/.git rev-parse --short HEAD) >> labels/labels
                echo revision_xhtml_validator=$(git --git-dir=source-code-xhtml-validator/.git rev-parse --short HEAD) >> labels/labels

                tag=$(date '+%Y%m%d.%H%M%S')
                echo "$tag" >> tags/tags
                echo master >> tags/tags
                echo trunk >> tags/tags

                cat tags/tags
                cat labels/labels
      - in_parallel:
          fail_fast: true
          limit: 2
          steps:
            - task: build-nebuchadnezzar
              privileged: true
              image: image-builder
              output_mapping: { image: built-image-nebuchadnezzar }
              config:
                params:
                  LABELS_FILE: labels/labels
                  DOCKER_CONFIG: docker-config
                  CONTEXT: source-code-nebuchadnezzar
                inputs:
                  - name: labels
                  - name: docker-config
                  - name: source-code-nebuchadnezzar
                <<: *image-build-config-common
            - task: build-cops-frontend
              privileged: true
              image: image-builder
              output_mapping: { image: built-image-cops-frontend }
              config:
                params:
                  LABELS_FILE: labels/labels
                  DOCKER_CONFIG: docker-config
                  CONTEXT: source-code-cops/frontend
                inputs:
                  - name: labels
                  - name: docker-config
                  - name: source-code-cops
                <<: *image-build-config-common
            - task: build-cops-backend
              privileged: true
              image: image-builder
              output_mapping: { image: built-image-cops-backend }
              config:
                params:
                  LABELS_FILE: labels/labels
                  DOCKER_CONFIG: docker-config
                  CONTEXT: source-code-cops/backend
                  DOCKERFILE: source-code-cops/backend/backend.dockerfile
                inputs:
                  - name: labels
                  - name: docker-config
                  - name: source-code-cops
                <<: *image-build-config-common
            - task: build-cops-bakery-scripts
              privileged: true
              image: image-builder
              output_mapping: { image: built-image-cops-bakery-scripts }
              config:
                params:
                  LABELS_FILE: labels/labels
                  DOCKER_CONFIG: docker-config
                  CONTEXT: source-code-cops/bakery/src/scripts
                inputs:
                  - name: labels
                  - name: docker-config
                  - name: source-code-cops
                <<: *image-build-config-common
            - task: build-mathify
              privileged: true
              image: image-builder
              output_mapping: { image: built-image-mathify }
              config:
                params:
                  LABELS_FILE: labels/labels
                  DOCKER_CONFIG: docker-config
                  CONTEXT: source-code-mathify
                inputs:
                  - name: labels
                  - name: docker-config
                  - name: source-code-mathify
                <<: *image-build-config-common
            - task: build-princexml
              privileged: true
              image: image-builder
              output_mapping: { image: built-image-princexml }
              config:
                params:
                  LABELS_FILE: labels/labels
                  DOCKER_CONFIG: docker-config
                  CONTEXT: source-code-princexml
                inputs:
                  - name: labels
                  - name: docker-config
                  - name: source-code-princexml
                <<: *image-build-config-common
            - task: build-cops-resource
              privileged: true
              image: image-builder
              output_mapping: { image: built-image-cops-resource }
              config:
                params:
                  LABELS_FILE: labels/labels
                  DOCKER_CONFIG: docker-config
                  CONTEXT: source-code-cops-resource
                inputs:
                  - name: labels
                  - name: docker-config
                  - name: source-code-cops-resource
                <<: *image-build-config-common
            - task: build-cnx-recipes-output
              privileged: true
              image: image-builder
              output_mapping: { image: built-image-cnx-recipes-output }
              config:
                params:
                  LABELS_FILE: labels/labels
                  DOCKER_CONFIG: docker-config
                  CONTEXT: source-code-cnx-recipes
                  DOCKERFILE: source-code-cnx-recipes/outputs.dockerfile
                inputs:
                  - name: labels
                  - name: docker-config
                  - name: source-code-cnx-recipes
                <<: *image-build-config-common
            - task: build-kitchen-recipes
              privileged: true
              image: image-builder
              output_mapping: { image: built-image-kitchen-recipes }
              config:
                params:
                  LABELS_FILE: labels/labels
                  DOCKER_CONFIG: docker-config
                  CONTEXT: source-code-kitchen-recipes
                  TARGET: runtime-env
                  DOCKERFILE: source-code-kitchen-recipes/docker/Dockerfile
                inputs:
                  - name: labels
                  - name: docker-config
                  - name: source-code-kitchen-recipes
                <<: *image-build-config-common
            - task: build-xthml-validator
              privileged: true
              image: image-builder
              output_mapping: { image: built-image-xhtml-validator }
              config:
                params:
                  LABELS_FILE: labels/labels
                  DOCKER_CONFIG: docker-config
                  CONTEXT: source-code-xhtml-validator
                inputs:
                  - name: labels
                  - name: docker-config
                  - name: source-code-xhtml-validator
                <<: *image-build-config-common
      - in_parallel:
          fail_fast: true
          limit: 2
          steps:
            - put: docker-hub-image-nebuchadnezzar
              params: 
                image: built-image-nebuchadnezzar/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: ecr-image-nebuchadnezzar
              params: 
                image: built-image-nebuchadnezzar/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: docker-hub-image-cops-frontend
              params: 
                image: built-image-cops-frontend/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: ecr-image-corgi-frontend
              params: 
                image: built-image-cops-frontend/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: docker-hub-image-cops-backend
              params: 
                image: built-image-cops-backend/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: ecr-image-corgi-backend
              params: 
                image: built-image-cops-backend/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: docker-hub-image-cops-bakery-scripts
              params: 
                image: built-image-cops-bakery-scripts/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: ecr-image-corgi-bakery-scripts
              params: 
                image: built-image-cops-bakery-scripts/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: docker-hub-image-mathify
              params: 
                image: built-image-mathify/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: ecr-image-mathify
              params: 
                image: built-image-mathify/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: docker-hub-image-princexml
              params: 
                image: built-image-princexml/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: ecr-image-princexml
              params: 
                image: built-image-princexml/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: docker-hub-image-cops-resource
              params: 
                image: built-image-cops-resource/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: ecr-image-corgi-resource
              params: 
                image: built-image-cops-resource/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: docker-hub-image-cnx-recipes-output
              params: 
                image: built-image-cnx-recipes-output/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: ecr-image-cnx-recipes-output
              params: 
                image: built-image-cnx-recipes-output/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: docker-hub-image-kitchen-recipes
              params:
                image: built-image-kitchen-recipes/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: ecr-image-kitchen-recipes
              params:
                image: built-image-kitchen-recipes/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: docker-hub-image-xhtml-validator
              params: 
                image: built-image-xhtml-validator/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
            - put: ecr-image-xhtml-validator
              params: 
                image: built-image-xhtml-validator/image.tar
                additional_tags: tags/tags
              get_params: { skip_download: true }
