---
tags-labels: &tags-labels
  tag_file: tag/tag
  additional_tags: tag/other
  labels_file: labels/labels
  tag_as_latest: false

use-trunk-cache: &use-trunk-cache
  cache: true
  cache_tag: trunk

docker-credentials: &docker-credentials
  username: ((docker-hub-username))
  password: ((docker-hub-password))

resources:
  # We leverage concourse's volume caching to provide the shared python:3.7-slim shared base
  - name: python-3.7-slim
    type: docker-image
    source:
      repository: python
      tag: 3.7-slim

  - name: source-code-nebuchadnezzar
    type: git
    source:
      uri: https://github.com/openstax/nebuchadnezzar.git
      branch: master
  - name: docker-hub-image-nebuchadnezzar
    type: docker-image
    source:
      repository: openstax/nebuchadnezzar
      <<: *docker-credentials

  - name: source-code-output-producer-service
    type: git
    source:
      uri: https://github.com/openstax/output-producer-service.git
      branch: master
  - name: docker-hub-image-output-producer-frontend
    type: docker-image
    source:
      repository: openstax/output-producer-frontend
      <<: *docker-credentials
  - name: docker-hub-image-output-producer-backend
    type: docker-image
    source:
      repository: openstax/output-producer-backend
      <<: *docker-credentials
  - name: docker-hub-image-cops-bakery-scripts
    type: docker-image
    source:
      repository: openstax/cops-bakery-scripts
      <<: *docker-credentials

  - name: source-code-cnx-easybake
    type: git
    source:
      uri: https://github.com/openstax/cnx-easybake.git
      branch: master
  - name: docker-hub-image-cnx-easybake
    type: docker-image
    source:
      repository: openstax/cnx-easybake
      <<: *docker-credentials

  - name: source-code-mathify
    type: git
    source:
      uri: https://github.com/openstax/mathify.git
      branch: master
  - name: docker-hub-image-mathify
    type: docker-image
    source:
      repository: openstax/mathify
      <<: *docker-credentials

  - name: source-code-princexml
    type: git
    source:
      uri: https://github.com/openstax/docker-princexml.git
      branch: master
  - name: docker-hub-image-princexml
    type: docker-image
    source:
      repository: openstax/princexml
      <<: *docker-credentials

  - name: source-code-output-producer-resource
    type: git
    source:
      uri: https://github.com/openstax/output-producer-resource.git
      branch: master
  - name: docker-hub-image-output-producer-resource
    type: docker-image
    source:
      repository: openstax/output-producer-resource
      <<: *docker-credentials

  - name: source-code-cnx-recipes
    type: git
    source:
      uri: https://github.com/openstax/cnx-recipes.git
      branch: master
      tag_filter: '*'
  - name: docker-hub-image-cnx-recipes-output
    type: docker-image
    source:
      repository: openstax/cnx-recipes-output
      <<: *docker-credentials

  - name: source-code-xhtml-validator
    type: git
    source:
      uri: https://github.com/openstax/xhtml-validator.git
      branch: trunk
  - name: docker-hub-image-xhtml-validator
    type: docker-image
    source:
      repository: openstax/xhtml-validator
      <<: *docker-credentials

jobs:
  - name: build-and-publish-images
    public: true
    serial: true
    plan:
      - in_parallel:
        - get: source-code-nebuchadnezzar
          trigger: true
        - get: source-code-output-producer-service
          trigger: true
        - get: source-code-cnx-easybake
          trigger: true
        - get: source-code-mathify
          trigger: true
        - get: source-code-princexml
          trigger: true
        - get: source-code-output-producer-resource
          trigger: true
        - get: source-code-cnx-recipes
          trigger: true
        - get: source-code-xhtml-validator
          trigger: true
        - get: python-3.7-slim
          params: {save: true}
      - task: report-versions-and-create-tag
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: alpine/git}
          inputs:
            - { name: source-code-nebuchadnezzar }
            - { name: source-code-output-producer-service }
            - { name: source-code-cnx-easybake }
            - { name: source-code-mathify }
            - { name: source-code-princexml }
            - { name: source-code-output-producer-resource }
            - { name: source-code-cnx-recipes }
            - { name: source-code-xhtml-validator }
          outputs: [{name: 'tag'}, {name: 'versions'}]
          run:
            path: /bin/sh
            args:
              - -cxe
              - |
                git --git-dir=source-code-nebuchadnezzar/.git rev-parse --short HEAD > versions/nebuchadnezzar
                git --git-dir=source-code-output-producer-service/.git rev-parse --short HEAD > versions/output-producer-service
                git --git-dir=source-code-cnx-easybake/.git rev-parse --short HEAD > versions/cnx-easybake
                git --git-dir=source-code-mathify/.git rev-parse --short HEAD > versions/mathify
                git --git-dir=source-code-princexml/.git rev-parse --short HEAD > versions/princexml
                git --git-dir=source-code-output-producer-resource/.git rev-parse --short HEAD > versions/output-producer-resource
                git --git-dir=source-code-cnx-recipes/.git describe > versions/cnx-recipes
                git --git-dir=source-code-xhtml-validator/.git rev-parse --short HEAD > versions/xhtml-validator

                tag=$(date '+%Y%m%d.%H%M%S')
                echo "$tag" > tag/tag
                echo master > tag/other
                echo trunk >> tag/other
      - task: create-versions-metadata
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: stedolan/jq}
          inputs: [{name: 'versions'}]
          outputs: [{name: 'labels'}]
          run:
            path: /bin/sh
            args:
              - -cxe
              - |
                jq -n \
                --arg version_neb $(cat versions/nebuchadnezzar) \
                --arg version_cops $(cat versions/output-producer-service) \
                --arg version_easybake $(cat versions/cnx-easybake) \
                --arg version_mathify $(cat versions/mathify) \
                --arg version_princexml $(cat versions/princexml) \
                --arg version_cops_resource $(cat versions/output-producer-resource) \
                --arg version_recipes $(cat versions/cnx-recipes) \
                --arg version_xhtml_validator $(cat versions/xhtml-validator) \
                '{ $version_neb, $version_cops, $version_easybake, $version_mathify, $version_princexml, $version_cops_resource, $version_recipes, $version_xhtml_validator }' \
                > labels/labels

                cat labels/labels
      - in_parallel:
          fail_fast: true
          limit: 4
          steps:
            - put: docker-hub-image-nebuchadnezzar
              params:
                build: source-code-nebuchadnezzar
                load_base: python-3.7-slim
                <<: *tags-labels
                <<: *use-trunk-cache
              get_params: {skip_download: true}
            - put: docker-hub-image-output-producer-frontend
              params:
                build: source-code-output-producer-service/frontend
                <<: *tags-labels
                <<: *use-trunk-cache
              get_params: {skip_download: true}
            - put: docker-hub-image-output-producer-backend
              params:
                build: source-code-output-producer-service/backend
                dockerfile: source-code-output-producer-service/backend/backend.dockerfile
                <<: *tags-labels
                <<: *use-trunk-cache
              get_params: {skip_download: true}
            - put: docker-hub-image-cops-bakery-scripts
              params:
                build: source-code-output-producer-service/bakery/src/scripts
                load_base: python-3.7-slim
                <<: *tags-labels
                <<: *use-trunk-cache
              get_params: {skip_download: true}
            - put: docker-hub-image-cnx-easybake
              params:
                build: source-code-cnx-easybake
                load_base: python-3.7-slim
                <<: *tags-labels
                <<: *use-trunk-cache
              get_params: {skip_download: true}
            - put: docker-hub-image-mathify
              params:
                build: source-code-mathify
                <<: *tags-labels
                <<: *use-trunk-cache
              get_params: {skip_download: true}
            - put: docker-hub-image-princexml
              params:
                build: source-code-princexml
                <<: *tags-labels
                <<: *use-trunk-cache
              get_params: {skip_download: true}
            - put: docker-hub-image-output-producer-resource
              params:
                build: source-code-output-producer-resource
                <<: *tags-labels
                <<: *use-trunk-cache
              get_params: {skip_download: true}
            - put: docker-hub-image-cnx-recipes-output
              params:
                build: source-code-cnx-recipes
                dockerfile: source-code-cnx-recipes/outputs.dockerfile
                <<: *tags-labels
              get_params: {skip_download: true}
            - put: docker-hub-image-xhtml-validator
              params:
                build: source-code-xhtml-validator
                <<: *tags-labels
              get_params: {skip_download: true}
