---
resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/openstax/((github-repo)).git

  - name: source-code-tagged
    type: git
    source:
      uri: https://github.com/openstax/((github-repo)).git
      tag_filter: '*'

  - name: docker-hub-image
    type: registry-image
    source:
      repository: openstax/((github-repo))
      username: ((docker-hub-username))
      password: ((docker-hub-password))

jobs:
  - name: build-and-publish-image
    public: true
    plan:
      - get: source-code
        trigger: true
      - task: create-tag-file
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: busybox}
          outputs: [{name: 'tag-file'}]
          run:
            path: /bin/sh
            args:
              - -cxe
              - |
                echo 'dev' > tag-file/tag
      - put: docker-hub-image
        params:
          build: source-code
          tag_file: tag-file/tag
          tag_as_latest: false
          get_params: {skip_download: true}

  - name: build-and-publish-tagged-image
    public: true
    plan:
      - get: source-code-tagged
        trigger: true
      - task: create-tag-file
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: alpine/git}
          inputs: [{name: 'source-code-tagged'}]
          outputs: [{name: 'tag-files'}]
          run:
            path: /bin/sh
            args:
              - -cxe
              - |
                touch tag-files/additional tag-files/current
                this_tag=$(git --git-dir source-code-tagged/.git describe --tags --abbrev=0)

                git --git-dir source-code-tagged/.git checkout master
                latest_tag=$(git --git-dir source-code-tagged/.git describe --tags --abbrev=0)
                git --git-dir source-code-tagged/.git checkout "$this_tag"

                echo "$this_tag" > tag-files/current
                if [ "$this_tag" = "$latest_tag" ]; then
                  echo 'latest' > tag-files/additional
                else
                  echo 'not latest'
                fi
      - put: docker-hub-image
        params:
          additional_tags: tag-files/additional
          build: source-code-tagged
          tag_file: tag-files/current
          tag_as_latest: false
          get_params: {skip_download: true}
